# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='cruft',
    version='1.1.2',
    description='Allows you to maintain all the necessary cruft for packaging and building projects separate from the code you intentionally write. Built on-top of CookieCutter.',
    python_requires='==3.*,>=3.6.0',
    author='Timothy Crosley',
    author_email='timothy.crosley@gmail.com',
    license='MIT',
    entry_points={"console_scripts": ["cruft = cruft.cli:hug_api.cli"]},
    packages=['cruft'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'cookiecutter==1.*,>=1.6.0', 'examples==1.*,>=1.0.0',
        'gitpython==3.*,>=3.0.0', 'hug==2.*,>=2.6.0'
    ],
    extras_require={
        "dev": [
            "bandit==1.*,>=1.6.0", "black==18.*,>=18.3.0",
            "flake8-bugbear==19.*,>=19.8.0", "hypothesis-auto==1.*,>=1.1.0",
            "ipython==7.*,>=7.7.0", "isort==4.*,>=4.3.0", "mypy==0.*,>=0.730.0",
            "numpy==1.*,>=1.17.0", "pep8-naming==0.*,>=0.8.2",
            "portray==1.*,>=1.3.0", "pydantic==0.*,>=0.32.0",
            "pytest==5.*,>=5.0.0", "pytest-cov==2.*,>=2.7.0",
            "pytest-mock==1.*,>=1.10.0", "safety==1.*,>=1.8.0",
            "vulture==1.*,>=1.0.0"
        ],
        "pyproject": ["toml==0.*,>=0.10.0"]
    },
)
