---
name: Docs publish

on:
  push:
    branches:
      - main
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry env use "3.8"
          poetry install

      - name: Deploy docs
        run: poetry run portray on_github_pages -f
