---
name: Test PyPI publish

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.8"
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Bump version number
        run: |
          sed -i "s/version = \".*\"/version = \"${{ github.event.release.tag_name }}\"/" pyproject.toml

      - name: Build package
        run: uv build

      - name: Publish package
        run: uv publish -u __token__ -p ${{ secrets.TEST_PYPI_PASSWORD }} --publish-url https://test.pypi.org/legacy/
